Repository PolyMC/PolyMC, pull requests merged in 2022-05, with the labels that each got.

#510 CI Speedup [1/3]: Use ccache to speed up CI builds
  .github/workflows/build.yml
Labels: enhancement, priority, actions

#503 Fix mnemonics that didn't parse
  launcher/ui/pages/global/ExternalToolsPage.ui
  launcher/ui/pages/global/JavaPage.ui
  launcher/ui/pages/global/ProxyPage.ui
  launcher/ui/widgets/CustomCommands.ui
Labels: bug

#557 CurseForge API Key update to PolyMC key
  CMakeLists.txt
Labels: priority, backport

#500 Refactor a little the code in `launcher/net/` files
  launcher/InstanceImportTask.cpp
  launcher/minecraft/AssetsUtils.cpp
  launcher/net/ByteArraySink.h
  launcher/net/ChecksumValidator.h
  launcher/net/Download.cpp
  launcher/net/Download.h
  launcher/net/FileSink.cpp
  launcher/net/FileSink.h
  launcher/net/HttpMetaCache.cpp
  launcher/net/HttpMetaCache.h
  launcher/net/MetaCacheSink.cpp
  launcher/net/MetaCacheSink.h
  launcher/net/Mode.h
  launcher/net/NetAction.h
  launcher/net/NetJob.cpp
  launcher/net/NetJob.h
  launcher/net/PasteUpload.cpp
  launcher/net/PasteUpload.h
  launcher/net/Sink.h
  launcher/net/Validator.h
  launcher/screenshots/ImgurAlbumCreation.cpp
  launcher/screenshots/ImgurAlbumCreation.h
  launcher/screenshots/ImgurUpload.cpp
  launcher/screenshots/ImgurUpload.h
  launcher/tasks/Task.cpp
  launcher/tasks/Task.h
  launcher/translations/TranslationsModel.cpp
Labels: enhancement

#576 Create Windows installer
  .github/workflows/build.yml
  .github/workflows/trigger_release.yml
  program_info/win_install.nsi
Labels: priority

#614 Avoid invoking ccache on Release builds
  .github/workflows/build.yml
Labels: bug

#597 Refactor ModLoaderType
  launcher/minecraft/PackProfile.cpp
  launcher/minecraft/PackProfile.h
  launcher/modplatform/ModAPI.h
  launcher/modplatform/flame/FlameAPI.h
  launcher/modplatform/modrinth/ModrinthAPI.h
  launcher/ui/pages/instance/ModFolderPage.cpp
  launcher/ui/pages/modplatform/ModModel.cpp
  launcher/ui/pages/modplatform/ModPage.cpp
  launcher/ui/pages/modplatform/ModPage.h
  launcher/ui/pages/modplatform/flame/FlameModPage.cpp
  launcher/ui/pages/modplatform/flame/FlameModPage.h
  launcher/ui/pages/modplatform/modrinth/ModrinthModPage.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthModPage.h
Labels: priority

#623 Add a .clang-format
  .clang-format
  .gitignore
Labels: enhancement

#629 Add desktop shortcut to Windows installer
  program_info/win_install.nsi
Labels: Windows

#639 Prefer stricter modpack formats during import
  launcher/InstanceImportTask.cpp
Labels: bug, enhancement

#625 Use light background macOS icon
  program_info/org.polymc.PolyMC.bigsur.svg
  program_info/polymc.icns
Labels: enhancement, macOS

#657 Fix crash when aborting instance import
  launcher/InstanceImportTask.cpp
Labels: bug

#650 Fix modpack icon importing with non-standard icon paths
  launcher/icons/IconList.cpp
Labels: bug

#651 Fix mnemonics in APIPage
  launcher/ui/pages/global/APIPage.ui
Labels: bug

#611 Rework curseforge download
  launcher/CMakeLists.txt
  launcher/InstanceImportTask.cpp
  launcher/InstanceImportTask.h
  launcher/modplatform/flame/FileResolvingTask.cpp
  launcher/modplatform/flame/FileResolvingTask.h
  launcher/modplatform/flame/PackManifest.cpp
  launcher/modplatform/flame/PackManifest.h
  launcher/net/Upload.cpp
  launcher/net/Upload.h
  launcher/ui/dialogs/ScrollMessageBox.cpp
  launcher/ui/dialogs/ScrollMessageBox.h
  launcher/ui/dialogs/ScrollMessageBox.ui
  launcher/ui/pages/modplatform/ImportPage.cpp
  launcher/ui/pages/modplatform/flame/FlamePage.cpp
Labels: bug, enhancement

#653 Nix updates
  default.nix
  flake.lock
  flake.nix
  nix/NIX.md
  nix/default.nix
  nix/flake-compat.nix
Labels: enhancement, packaging

#661 Update whitelisted hosts in Modrinth modpacks
  launcher/InstanceImportTask.cpp
  launcher/modplatform/modrinth/ModrinthPackManifest.cpp
Labels: external

#624 Make global JVM arguments multi-line
  launcher/ui/pages/global/JavaPage.cpp
  launcher/ui/pages/global/JavaPage.ui
Labels: enhancement

#674 remove unnecessary translation
  launcher/ui/dialogs/ScrollMessageBox.ui
Labels: bug
