Repository PolyMC/PolyMC, pull requests merged in 2022-03, with the labels that each got.

#163 Replace build layouts with Launcher_PORTABLE cmake flag
  .github/workflows/build.yml
  BUILD.md
  CMakeLists.txt
  launcher/Application.cpp
  packages/nix/polymc/default.nix
Labels: enhancement, high, needs-review, needs-testing:windows, needs-testing:macOS

#205 Fixed wrong version info
  launcher/ui/pages/modplatform/flame/FlameModPage.cpp
  launcher/ui/pages/modplatform/flame/FlamePage.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
Labels: needs-review

#216 Don't build when updating non-code
  .github/workflows/trigger_builds.yml
Labels: GHA

#230 Reorganize icon themes
  launcher/ui/pages/global/LauncherPage.cpp
  launcher/ui/pages/global/LauncherPage.ui
Labels: enhancement

#232 Switch to polymc.org wiki
  CMakeLists.txt
  buildconfig/BuildConfig.cpp.in
  buildconfig/BuildConfig.h
  launcher/ui/widgets/PageContainer.cpp
Labels: enhancement

#247 Fix Ubuntu system Qt failure
  .github/workflows/build.yml
Labels: priority, actions

#235 Bump to 1.1.0
  CMakeLists.txt
Labels: priority

#294 Switch to msys2 for Windows builds
  .github/workflows/build.yml
Labels: actions

#315 Allow fractional DPI scaling
  launcher/main.cpp
Labels: bug

#349 Avoid building per-commit release type builds
  .github/workflows/trigger_builds.yml
Labels: actions

#344 Allow disabling test building
  CMakeLists.txt
  cmake/UnitTest.cmake
  launcher/CMakeLists.txt
Labels: enhancement
