Repository PolyMC/PolyMC, pull requests merged in 2022-04, with the labels that each got.

#175 Allow components to specify Java agents and JVM arguments
  launcher/CMakeLists.txt
  launcher/minecraft/Agent.h
  launcher/minecraft/LaunchProfile.cpp
  launcher/minecraft/LaunchProfile.h
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/OneSixVersionFormat.cpp
  launcher/minecraft/VersionFile.cpp
  launcher/minecraft/VersionFile.h
  launcher/minecraft/update/LibrariesTask.cpp
  launcher/ui/widgets/CustomCommands.ui
Labels: enhancement

#397 Detect 64bit ARM [from ManyMC]
  launcher/java/JavaChecker.cpp
  launcher/java/JavaInstallList.cpp
  launcher/launch/steps/CheckJava.cpp
Labels: enhancement

#384 Technic: Display available versions for Solder packs
  buildconfig/BuildConfig.h
  launcher/CMakeLists.txt
  launcher/modplatform/technic/SolderPackInstallTask.cpp
  launcher/modplatform/technic/SolderPackInstallTask.h
  launcher/modplatform/technic/SolderPackManifest.cpp
  launcher/modplatform/technic/SolderPackManifest.h
  launcher/ui/pages/modplatform/technic/TechnicData.h
  launcher/ui/pages/modplatform/technic/TechnicModel.cpp
  launcher/ui/pages/modplatform/technic/TechnicModel.h
  launcher/ui/pages/modplatform/technic/TechnicPage.cpp
  launcher/ui/pages/modplatform/technic/TechnicPage.h
  launcher/ui/pages/modplatform/technic/TechnicPage.ui
Labels: enhancement

#380 Improve the progress dialog when there's multiple tasks
  launcher/tasks/SequentialTask.cpp
  launcher/tasks/SequentialTask.h
  launcher/tasks/Task.h
  launcher/ui/dialogs/ProgressDialog.cpp
  launcher/ui/dialogs/ProgressDialog.h
  launcher/ui/dialogs/ProgressDialog.ui
  launcher/ui/pages/instance/ModFolderPage.cpp
Labels: bug

#364 Fix translatable strings 2
  launcher/ui/dialogs/AboutDialog.ui
  launcher/ui/dialogs/UpdateDialog.ui
  launcher/ui/pages/global/MinecraftPage.ui
Labels: enhancement

#272 nix: refactor flake (drop flake-utils)
  flake.lock
  flake.nix
  packages/nix/polymc/default.nix
Labels: packaging

#409 Fix some issues with Tasks and add unit test
  launcher/CMakeLists.txt
  launcher/InstanceImportTask.cpp
  launcher/InstanceImportTask.h
  launcher/tasks/Task.h
  launcher/tasks/Task_test.cpp
Labels: bug

#185 Quilt support
  launcher/InstanceImportTask.cpp
  launcher/minecraft/ComponentUpdateTask.cpp
  launcher/minecraft/PackProfile.cpp
  launcher/minecraft/PackProfile.h
  launcher/minecraft/mod/LocalModParseTask.cpp
  launcher/modplatform/ModAPI.h
  launcher/modplatform/flame/FlameModIndex.cpp
  launcher/modplatform/modrinth/ModrinthAPI.h
  launcher/ui/pages/instance/ModFolderPage.cpp
  launcher/ui/pages/instance/VersionPage.cpp
  launcher/ui/pages/instance/VersionPage.h
  launcher/ui/pages/instance/VersionPage.ui
  launcher/ui/pages/modplatform/ModModel.cpp
  launcher/ui/pages/modplatform/ModModel.h
  launcher/ui/pages/modplatform/ModPage.cpp
Labels: enhancement, meta

#398 Add option to install mod loader during instance creation
  launcher/InstanceCreationTask.cpp
  launcher/InstanceCreationTask.h
  launcher/ui/pages/modplatform/VanillaPage.cpp
  launcher/ui/pages/modplatform/VanillaPage.h
  launcher/ui/pages/modplatform/VanillaPage.ui
  launcher/ui/widgets/VersionSelectWidget.cpp
  launcher/ui/widgets/VersionSelectWidget.h
Labels: enhancement

#392 Add basic filtering for mod downloading
  launcher/CMakeLists.txt
  launcher/modplatform/ModAPI.h
  launcher/modplatform/flame/FlameAPI.h
  launcher/modplatform/modrinth/ModrinthAPI.h
  launcher/ui/dialogs/ModDownloadDialog.cpp
  launcher/ui/pages/modplatform/ModModel.cpp
  launcher/ui/pages/modplatform/ModModel.h
  launcher/ui/pages/modplatform/ModPage.cpp
  launcher/ui/pages/modplatform/ModPage.h
  launcher/ui/pages/modplatform/ModPage.ui
  launcher/ui/widgets/ModFilterWidget.cpp
  launcher/ui/widgets/ModFilterWidget.h
  launcher/ui/widgets/ModFilterWidget.ui
Labels: enhancement

#429 better FreeBSD support
  launcher/minecraft/MinecraftInstance.cpp
Labels: enhancement

#336 Combine portable and system builds
  .github/workflows/build.yml
  CMakeLists.txt
  launcher/Application.cpp
  launcher/CMakeLists.txt
  launcher/Launcher.in
  program_info/CMakeLists.txt
  program_info/portable.txt
Labels: packaging

#443 Don't translate placeholders in ModFilterWidget
  launcher/ui/widgets/ModFilterWidget.ui
Labels: bug

#442 Fix typos and inconsistent capitalization in sort options
  launcher/ui/pages/modplatform/atlauncher/AtlFilterModel.cpp
  launcher/ui/pages/modplatform/flame/FlameModPage.cpp
  launcher/ui/pages/modplatform/flame/FlamePage.cpp
  launcher/ui/pages/modplatform/ftb/FtbFilterModel.cpp
  launcher/ui/pages/modplatform/legacy_ftb/ListModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
Labels: bug

#449 specify -DLauncher_BUILD_PLATFORM on CI builds (EDIT: also remove "on x")
  .github/workflows/build.yml
  launcher/ui/MainWindow.cpp
Labels: enhancement

#455 Fix formatting of version string on macOS
  CMakeLists.txt
Labels: bug

#450 Fix Modrinth query when Quilt is in use
  launcher/modplatform/modrinth/ModrinthAPI.h
  launcher/ui/pages/modplatform/ModPage.cpp
  launcher/ui/pages/modplatform/ModPage.h
  launcher/ui/pages/modplatform/flame/FlameModPage.cpp
  launcher/ui/pages/modplatform/flame/FlameModPage.h
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.h
Labels: bug

#444 Fix release workflow
  .github/workflows/build.yml
  .github/workflows/trigger_release.yml
Labels: bug

#451 Actually check if a mod loader is selected when creating an instance
  launcher/InstanceCreationTask.cpp
  launcher/ui/pages/modplatform/VanillaPage.cpp
Labels: bug

#452 Handle network errors when downloading modlist
  launcher/ui/pages/modplatform/ModModel.cpp
Labels: bug

#454 Improve security by enabling hardened runtime for macOS
  .github/workflows/build.yml
  cmake/MacOSXBundleInfo.plist.in
  program_info/App.entitlements
Labels: enhancement

#462 fix: use size in bytes to sort by world size
  launcher/minecraft/WorldList.cpp
  launcher/ui/pages/instance/WorldListPage.cpp
Labels: bug

#463 Only trigger macOS instance rename on KeyDown
  launcher/ui/instanceview/InstanceDelegate.cpp
Labels: bug

#467 Revert "better FreeBSD support"
  launcher/minecraft/MinecraftInstance.cpp
Labels: bug

#408 ATLauncher: Support using share codes
  buildconfig/BuildConfig.h
  launcher/CMakeLists.txt
  launcher/modplatform/atlauncher/ATLShareCode.cpp
  launcher/modplatform/atlauncher/ATLShareCode.h
  launcher/ui/pages/modplatform/atlauncher/AtlOptionalModDialog.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlOptionalModDialog.h
  launcher/ui/pages/modplatform/atlauncher/AtlOptionalModDialog.ui
Labels: enhancement
