Repository PolyMC/PolyMC, pull requests merged in 2022-08, with the labels that each got.

#1008 chore: update issue template to ask about Qt version
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: simple change

#1012 fix: remove iconfix from libraries/README.MD
  libraries/README.md
Labels: simple change

#994 Fix WinGet releaser
  .github/workflows/winget.yml
Labels: bug, actions, simple change

#1019 Add root path detection on OpenBSD
  launcher/Application.cpp
Labels: bug, simple change

#1006 fix: work around ubuntu 22.04 openssl appimage issues by copying openssl libs
  .github/workflows/build.yml
Labels: bug, packaging

#1014 chore: downgrade to Qt 6.3.0 on macos
  .github/workflows/build.yml
Labels: bug, packaging, macOS

#1017 Remove orphaned metadata to avoid problems with auto-updating instances
  launcher/minecraft/mod/tasks/ModFolderLoadTask.cpp
Labels: bug

#1018 Allow user to interrupt launch after 3 tries
  launcher/Application.cpp
  launcher/LaunchController.cpp
Labels: bug

#920 Fix some icon cache problems
  launcher/Application.cpp
  launcher/net/HttpMetaCache.cpp
  launcher/net/HttpMetaCache.h
  launcher/net/MetaCacheSink.cpp
Labels: bug

#909 Run markdownlint on the markdown files
  .github/workflows/trigger_builds.yml
  .markdownlint.yaml
  .markdownlintignore
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  COPYING.md
  README.md
  libraries/README.md
  libraries/katabasis/README.md
  libraries/katabasis/acknowledgements.md
  libraries/tomlc99/README.md
  nix/NIX.md
  program_info/README.md
Labels: enhancement

#1039 fix: Make world safety nag popup title text match the action
  launcher/ui/pages/instance/WorldListPage.cpp
  launcher/ui/pages/instance/WorldListPage.h
Labels: enhancement, simple change

#968 Decode process lines as UTF-8
  launcher/LoggedProcess.cpp
  launcher/LoggedProcess.h
Labels: bug

#1049 Hide 'More news...' button if the news aren't loaded yet
  launcher/ui/MainWindow.cpp
Labels: bug, simple change

#1058 fix: update org.polymc.PolyMC.metainfo.xml.in to not make flatpak break next release
  program_info/org.polymc.PolyMC.metainfo.xml.in
Labels: packaging

#919 Add "Open All" button to blocked mods dialog
  launcher/CMakeLists.txt
  launcher/InstanceImportTask.cpp
  launcher/modplatform/modpacksch/FTBPackInstallTask.cpp
  launcher/ui/dialogs/BlockedModsDialog.cpp
  launcher/ui/dialogs/BlockedModsDialog.h
  launcher/ui/dialogs/BlockedModsDialog.ui
Labels: enhancement

#1007 Disable "Check for Updates" while the game is running or if all mods are removed
  launcher/ui/pages/instance/ExternalResourcesPage.cpp
  launcher/ui/pages/instance/ExternalResourcesPage.h
  launcher/ui/pages/instance/ModFolderPage.cpp
  launcher/ui/pages/instance/ModFolderPage.h
Labels: bug, enhancement

#992 Switch to new versioning scheme
  CMakeLists.txt
  buildconfig/BuildConfig.cpp.in
  buildconfig/BuildConfig.h
  launcher/Application.cpp
  launcher/ui/dialogs/AboutDialog.cpp
  launcher/ui/dialogs/AboutDialog.ui
  launcher/updater/UpdateChecker.cpp
  launcher/updater/UpdateChecker.h
  program_info/CMakeLists.txt
  program_info/org.polymc.PolyMC.metainfo.xml.in
  program_info/polymc.manifest.in
  program_info/polymc.rc.in
  program_info/win_install.nsi.in
Labels: packaging

#1044 Only remove orphaned metadata once on mod page opening
  launcher/minecraft/mod/ModFolderModel.cpp
  launcher/minecraft/mod/ModFolderModel.h
  launcher/minecraft/mod/tasks/ModFolderLoadTask.cpp
  launcher/minecraft/mod/tasks/ModFolderLoadTask.h
Labels: bug

#1023 Use QSharedPointer instead of own impl. for shared_qobject_ptr
  launcher/QObjectPtr.h
  launcher/minecraft/MinecraftUpdate.cpp
  launcher/minecraft/MinecraftUpdate.h
  launcher/minecraft/auth/MinecraftAccount.cpp
  launcher/ui/dialogs/LoginDialog.cpp
  launcher/ui/dialogs/MSALoginDialog.cpp
  launcher/ui/dialogs/OfflineLoginDialog.cpp
Labels: bug

#878 Lazy-load type-specific instance settings
  launcher/BaseInstance.cpp
  launcher/BaseInstance.h
  launcher/NullInstance.h
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/MinecraftInstance.h
  launcher/settings/SettingsObject.h
Labels: enhancement

#1035 Make Coremods / Mods seperation more clear
  launcher/ui/pages/instance/ModFolderPage.cpp
  launcher/ui/pages/instance/ModFolderPage.h
Labels: bug

#1087 fix: fix urls on ftb legacy
  launcher/ui/pages/modplatform/legacy_ftb/Page.ui
Labels: bug, simple change

#965 Refactor a bit EnsureMetadataTask and calculate hashes in a incremental manner
  launcher/CMakeLists.txt
  launcher/modplatform/EnsureMetadataTask.cpp
  launcher/modplatform/EnsureMetadataTask.h
  launcher/modplatform/ModIndex.cpp
  launcher/modplatform/ModIndex.h
  launcher/modplatform/helpers/HashUtils.cpp
  launcher/modplatform/helpers/HashUtils.h
  launcher/modplatform/modrinth/ModrinthCheckUpdate.cpp
  launcher/tasks/ConcurrentTask.cpp
  launcher/ui/dialogs/ModUpdateDialog.cpp
  libraries/murmur2/src/MurmurHash2.cpp
  libraries/murmur2/src/MurmurHash2.h
Labels: bug

#1052 Refactor resource models
  launcher/CMakeLists.txt
  launcher/InstancePageProvider.h
  launcher/MMCZip.cpp
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/MinecraftInstance.h
  launcher/minecraft/mod/Mod.cpp
  launcher/minecraft/mod/Mod.h
  launcher/minecraft/mod/ModDetails.h
  launcher/minecraft/mod/ModFolderModel.cpp
  launcher/minecraft/mod/ModFolderModel.h
  launcher/minecraft/mod/ModFolderModel_test.cpp
  launcher/minecraft/mod/Resource.cpp
  launcher/minecraft/mod/Resource.h
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/minecraft/mod/ResourceFolderModel.h
  launcher/minecraft/mod/ResourceFolderModel_test.cpp
  launcher/minecraft/mod/ResourcePack.h
  launcher/minecraft/mod/ResourcePackFolderModel.cpp
  launcher/minecraft/mod/ResourcePackFolderModel.h
  launcher/minecraft/mod/ShaderPackFolderModel.h
  launcher/minecraft/mod/TexturePackFolderModel.cpp
  launcher/minecraft/mod/TexturePackFolderModel.h
  launcher/minecraft/mod/tasks/BasicFolderLoadTask.h
  launcher/minecraft/mod/tasks/LocalModParseTask.cpp
  launcher/minecraft/mod/tasks/LocalModParseTask.h
  launcher/minecraft/mod/tasks/ModFolderLoadTask.cpp
  launcher/minecraft/mod/tasks/ModFolderLoadTask.h
  launcher/minecraft/mod/testdata/supercoolmod.jar
  launcher/modplatform/EnsureMetadataTask.cpp
  launcher/tasks/Task.cpp
  launcher/tasks/Task.h
  launcher/ui/dialogs/ModUpdateDialog.cpp
  launcher/ui/dialogs/ModUpdateDialog.h
  launcher/ui/pages/instance/ExternalResourcesPage.cpp
  launcher/ui/pages/instance/ExternalResourcesPage.h
  launcher/ui/pages/instance/ExternalResourcesPage.ui
  launcher/ui/pages/instance/ModFolderPage.cpp
  launcher/ui/pages/instance/ModFolderPage.h
  launcher/ui/pages/instance/ResourcePackPage.h
  launcher/ui/pages/instance/ShaderPackPage.h
  launcher/ui/pages/instance/TexturePackPage.h
  launcher/ui/pages/instance/VersionPage.cpp
  launcher/ui/pages/instance/VersionPage.ui
  launcher/ui/widgets/InfoFrame.cpp
  launcher/ui/widgets/InfoFrame.h
  launcher/ui/widgets/InfoFrame.ui
Labels: help wanted, rfc, needs testing

#1094 Fix build
  launcher/modplatform/EnsureMetadataTask.cpp
Labels: bug, simple change

#1080 Never invalidate libraries cache entries by time elapsed
  launcher/minecraft/Library.cpp
  launcher/minecraft/update/FMLLibrariesTask.cpp
  launcher/net/Download.cpp
  launcher/net/Download.h
  launcher/net/HttpMetaCache.cpp
  launcher/net/HttpMetaCache.h
  launcher/net/MetaCacheSink.cpp
  launcher/net/MetaCacheSink.h
Labels: bug

#1067 Move classpath definition into NewLaunch itself
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/launch/LauncherPartLaunch.cpp
  libraries/launcher/org/polymc/impl/OneSixLauncher.java
Labels: enhancement
