Repository PolyMC/PolyMC, pull requests merged in 2022-10, with the labels that each got.

#1167 Switch to QCommandLineParser
  launcher/Application.cpp
  launcher/Commandline.cpp
  launcher/Commandline.h
Labels: enhancement

#1171 Update winget.yml
  .github/workflows/winget.yml
Labels: actions, Windows, simple change

#1154 Support more formatting codes
  launcher/ui/widgets/InfoFrame.cpp
Labels: bug, enhancement

#1163 Fix mod icon issues and change delegate for Modrinth Modpacks
  launcher/ui/pages/modplatform/ModModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
  launcher/ui/widgets/ProjectItem.cpp
Labels: bug, enhancement

#1183 Update capabilities before first-run wizard
  launcher/Application.cpp
Labels: bug, simple change

#1174 Improve default light and dark themes
  launcher/ui/themes/BrightTheme.cpp
  launcher/ui/themes/DarkTheme.cpp
Labels: enhancement

#1185 fix: mod updating isn't upcoming anymore :p
  launcher/ui/pages/global/LauncherPage.ui
Labels: bug, simple change

#1190 Merge Launch Buttons
  launcher/ui/MainWindow.cpp
Labels: enhancement, simple change

#1194 Remove opted out versions from the download selector when using the 'Any' filter
  launcher/ui/pages/modplatform/ModPage.cpp
  launcher/ui/pages/modplatform/ModPage.h
  launcher/ui/pages/modplatform/flame/FlameModPage.cpp
  launcher/ui/pages/modplatform/flame/FlameModPage.h
Labels: bug, simple change

#1208 fix: remove some unused libs
  CMakeLists.txt
  launcher/CMakeLists.txt
  libraries/README.md
  libraries/classparser/CMakeLists.txt
  libraries/classparser/include/classparser.h
  libraries/classparser/include/classparser_config.h
  libraries/classparser/src/annotations.cpp
  libraries/classparser/src/annotations.h
  libraries/classparser/src/classfile.h
  libraries/classparser/src/classparser.cpp
  libraries/classparser/src/constants.h
  libraries/classparser/src/errors.h
  libraries/classparser/src/javaendian.h
  libraries/classparser/src/membuffer.h
  libraries/xz-embedded/CMakeLists.txt
  libraries/xz-embedded/include/xz.h
  libraries/xz-embedded/src/xz_config.h
  libraries/xz-embedded/src/xz_crc32.c
  libraries/xz-embedded/src/xz_crc64.c
  libraries/xz-embedded/src/xz_dec_bcj.c
  libraries/xz-embedded/src/xz_dec_lzma2.c
  libraries/xz-embedded/src/xz_dec_stream.c
  libraries/xz-embedded/src/xz_lzma2.h
  libraries/xz-embedded/src/xz_private.h
  libraries/xz-embedded/src/xz_stream.h
  libraries/xz-embedded/xzminidec.c
Labels: enhancement, simple change
