Repository PolyMC/PolyMC, pull requests merged in 2022-09, with the labels that each got.

#1095 Ensure individual destination file path exists in FS::overrideFolder
  launcher/FileSystem.cpp
Labels: bug, simple change

#1107 make the about dialog smaller
  launcher/ui/dialogs/AboutDialog.ui
Labels: bug

#1111 Revert "Move classpath definition into NewLaunch itself"
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/launch/LauncherPartLaunch.cpp
  libraries/launcher/org/polymc/impl/OneSixLauncher.java
Labels: bug

#1114 chore: update install-qt-action to v3
  .github/workflows/build.yml
Labels: actions

#1113 Fixed up a warning
  launcher/modplatform/atlauncher/ATLPackInstallTask.cpp
Labels: simple change

#966 Reduce code duplication in tasks, fix some bugs and add some tests
  launcher/net/NetAction.h
  launcher/net/NetJob.cpp
  launcher/net/NetJob.h
  launcher/tasks/ConcurrentTask.cpp
  launcher/tasks/ConcurrentTask.h
  launcher/tasks/MultipleOptionsTask.cpp
  launcher/tasks/MultipleOptionsTask.h
  launcher/tasks/SequentialTask.cpp
  launcher/tasks/SequentialTask.h
  launcher/tasks/Task_test.cpp
  launcher/ui/pages/modplatform/ModModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.cpp
Labels: enhancement

#939 Some more UI / UX improvements to the mod downloader!
  launcher/Application.cpp
  launcher/CMakeLists.txt
  launcher/modplatform/ModAPI.h
  launcher/modplatform/ModIndex.h
  launcher/modplatform/flame/FlameAPI.cpp
  launcher/modplatform/flame/FlameAPI.h
  launcher/modplatform/flame/FlameModIndex.cpp
  launcher/modplatform/flame/FlameModIndex.h
  launcher/modplatform/helpers/NetworkModAPI.cpp
  launcher/modplatform/helpers/NetworkModAPI.h
  launcher/modplatform/modrinth/ModrinthPackIndex.cpp
  launcher/ui/dialogs/ModDownloadDialog.cpp
  launcher/ui/dialogs/ModDownloadDialog.h
  launcher/ui/dialogs/ReviewMessageBox.cpp
  launcher/ui/pages/modplatform/ModModel.cpp
  launcher/ui/pages/modplatform/ModModel.h
  launcher/ui/pages/modplatform/ModPage.cpp
  launcher/ui/pages/modplatform/ModPage.h
  launcher/ui/pages/modplatform/flame/FlameModModel.cpp
  launcher/ui/pages/modplatform/flame/FlameModModel.h
  launcher/ui/widgets/Common.cpp
  launcher/ui/widgets/Common.h
  launcher/ui/widgets/PageContainer.cpp
  launcher/ui/widgets/PageContainer.h
  launcher/ui/widgets/ProgressWidget.cpp
  launcher/ui/widgets/ProgressWidget.h
  launcher/ui/widgets/ProjectItem.cpp
  launcher/ui/widgets/ProjectItem.h
Labels: enhancement

#1105 Add basic resource pack parsing and fix issues
  launcher/CMakeLists.txt
  launcher/minecraft/mod/ModFolderModel.cpp
  launcher/minecraft/mod/ModFolderModel.h
  launcher/minecraft/mod/Resource.h
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/minecraft/mod/ResourceFolderModel.h
  launcher/minecraft/mod/ResourceFolderModel_test.cpp
  launcher/minecraft/mod/ResourcePack.cpp
  launcher/minecraft/mod/ResourcePack.h
  launcher/minecraft/mod/ResourcePackFolderModel.cpp
  launcher/minecraft/mod/ResourcePackFolderModel.h
  launcher/minecraft/mod/ResourcePackParse_test.cpp
  launcher/minecraft/mod/tasks/BasicFolderLoadTask.h
  launcher/minecraft/mod/tasks/LocalModParseTask.cpp
  launcher/minecraft/mod/tasks/LocalModParseTask.h
  launcher/minecraft/mod/tasks/LocalResourcePackParseTask.cpp
  launcher/minecraft/mod/tasks/LocalResourcePackParseTask.h
  launcher/minecraft/mod/tasks/ModFolderLoadTask.cpp
  launcher/minecraft/mod/tasks/ModFolderLoadTask.h
  launcher/minecraft/mod/testdata/another_test_folder/pack.mcmeta
  launcher/minecraft/mod/testdata/test_resource_pack_idk.zip
  launcher/ui/pages/instance/ModFolderPage.cpp
  launcher/ui/pages/instance/ModFolderPage.h
  launcher/ui/pages/instance/ResourcePackPage.h
  launcher/ui/widgets/InfoFrame.cpp
  launcher/ui/widgets/InfoFrame.h
  launcher/ui/widgets/InfoFrame.ui
Labels: bug, enhancement

#997 Use MC versions list instead of ad-hoc logic to filter by major version in the mod downloader
  launcher/meta/VersionList.cpp
  launcher/meta/VersionList.h
  launcher/ui/dialogs/ModDownloadDialog.cpp
  launcher/ui/pages/modplatform/ModPage.cpp
  launcher/ui/pages/modplatform/ModPage.h
  launcher/ui/pages/modplatform/flame/FlameModPage.h
  launcher/ui/pages/modplatform/modrinth/ModrinthModPage.h
  launcher/ui/widgets/ModFilterWidget.cpp
  launcher/ui/widgets/ModFilterWidget.h
Labels: bug

#1117 Fix the mod updater not working as intended
  launcher/tasks/ConcurrentTask.cpp
Labels: bug, simple change

#1118 Backport #997 to 1.4.2
  launcher/meta/VersionList.cpp
  launcher/meta/VersionList.h
  launcher/ui/dialogs/ModDownloadDialog.cpp
  launcher/ui/pages/modplatform/ModPage.cpp
  launcher/ui/pages/modplatform/ModPage.h
  launcher/ui/pages/modplatform/flame/FlameModPage.h
  launcher/ui/pages/modplatform/modrinth/ModrinthModPage.h
  launcher/ui/widgets/ModFilterWidget.cpp
  launcher/ui/widgets/ModFilterWidget.h
Labels: bug, priority

#1123 Emit correct signals on NetJob abort
  launcher/net/NetJob.cpp
Labels: bug, simple change

#1133 Restructure tests
  CMakeLists.txt
  launcher/CMakeLists.txt
  tests/CMakeLists.txt
  tests/FileSystem_test.cpp
  tests/GZip_test.cpp
  tests/GradleSpecifier_test.cpp
  tests/INIFile_test.cpp
  tests/Index_test.cpp
  tests/JavaVersion_test.cpp
  tests/Library_test.cpp
  tests/MojangVersionFormat_test.cpp
  tests/PackageManifest_test.cpp
  tests/Packwiz_test.cpp
  tests/ParseUtils_test.cpp
  tests/ResourceFolderModel_test.cpp
  tests/ResourcePackParse_test.cpp
  tests/Task_test.cpp
  tests/Version_test.cpp
  tests/testdata/FileSystem/FileSystem-test_createShortcut-unix
  tests/testdata/FileSystem/test_folder/assets/minecraft/textures/blah.txt
  tests/testdata/FileSystem/test_folder/pack.mcmeta
  tests/testdata/FileSystem/test_folder/pack.nfo
  tests/testdata/Library
  tests/testdata/MojangVersionFormat/1.9-simple.json
  tests/testdata/MojangVersionFormat/1.9.json
  tests/testdata/MojangVersionFormat/codecwav-20101023.jar
  tests/testdata/MojangVersionFormat/lib-native-arch.json
  tests/testdata/MojangVersionFormat/lib-native.json
  tests/testdata/MojangVersionFormat/lib-simple.json
  tests/testdata/MojangVersionFormat/testname-testversion-linux-32.jar
  tests/testdata/PackageManifest/1.8.0_202-x64.json
  tests/testdata/PackageManifest/inspect/a/b.txt
  tests/testdata/PackageManifest/inspect/a/b/b.txt
  tests/testdata/PackageManifest/inspect_win/a/b.txt
  tests/testdata/PackageManifest/inspect_win/a/b/b.txt
  tests/testdata/Packwiz/borderless-mining.pw.toml
  tests/testdata/Packwiz/screenshot-to-clipboard-fabric.pw.toml
  tests/testdata/ResourceFolderModel
  tests/testdata/ResourcePackParse/another_test_folder/pack.mcmeta
  tests/testdata/ResourcePackParse/supercoolmod.jar
  tests/testdata/ResourcePackParse/test_folder/assets/minecraft/textures/blah.txt
  tests/testdata/ResourcePackParse/test_folder/pack.mcmeta
  tests/testdata/ResourcePackParse/test_folder/pack.nfo
  tests/testdata/ResourcePackParse/test_resource_pack_idk.zip
Labels: bug

#982 Feature: Enable dark titlebar on Windows 10 (3)
  launcher/Application.cpp
  launcher/CMakeLists.txt
  launcher/ui/WinDarkmode.cpp
  launcher/ui/WinDarkmode.h
Labels: enhancement, Windows

#1146 fix: allow starting rd- versions
  libraries/launcher/org/polymc/impl/OneSixLauncher.java
Labels: bug, simple change

#903 Added a button to launch in Demo mode
  launcher/Application.cpp
  launcher/Application.h
  launcher/LaunchController.cpp
  launcher/LaunchController.h
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/MinecraftInstance.h
  launcher/ui/InstanceWindow.cpp
  launcher/ui/InstanceWindow.h
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
  launcher/ui/pages/instance/ServersPage.cpp
  libraries/launcher/org/polymc/applet/LegacyFrame.java
  libraries/launcher/org/polymc/impl/OneSixLauncher.java
Labels: enhancement

#1142 Use std::filesystem in some filesystem utils
  .github/workflows/build.yml
  launcher/FileSystem.cpp
  tests/FileSystem_test.cpp
Labels: enhancement

#1150 Fix crash and memory leak because of Resources
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/mod/ModFolderModel.cpp
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/minecraft/mod/ResourceFolderModel.h
  launcher/minecraft/mod/tasks/BasicFolderLoadTask.h
  launcher/minecraft/mod/tasks/ModFolderLoadTask.cpp
  launcher/minecraft/mod/tasks/ModFolderLoadTask.h
Labels: bug

#1108 Add basic texture pack parsing
  launcher/CMakeLists.txt
  launcher/minecraft/mod/ModFolderModel.cpp
  launcher/minecraft/mod/ResourceFolderModel.cpp
  launcher/minecraft/mod/TexturePack.cpp
  launcher/minecraft/mod/TexturePack.h
  launcher/minecraft/mod/TexturePackFolderModel.cpp
  launcher/minecraft/mod/TexturePackFolderModel.h
  launcher/minecraft/mod/tasks/LocalTexturePackParseTask.cpp
  launcher/minecraft/mod/tasks/LocalTexturePackParseTask.h
  launcher/ui/pages/instance/TexturePackPage.h
  launcher/ui/widgets/InfoFrame.cpp
  launcher/ui/widgets/InfoFrame.h
  tests/CMakeLists.txt
  tests/ResourceFolderModel_test.cpp
  tests/TexturePackParse_test.cpp
  tests/testdata/TexturePackParse/another_test_texturefolder/pack.txt
  tests/testdata/TexturePackParse/test_texture_pack_idk.zip
  tests/testdata/TexturePackParse/test_texturefolder/assets/minecraft/textures/blah.txt
  tests/testdata/TexturePackParse/test_texturefolder/pack.txt
Labels: enhancement

#1165 Allows double clicking to mark for download
  launcher/ui/pages/modplatform/ModPage.cpp
Labels: enhancement, simple change

#1164 Improve language model
  launcher/translations/TranslationsModel.cpp
Labels: bug, enhancement, simple change

#894 Add early modpack updating system
  launcher/BaseInstance.cpp
  launcher/BaseInstance.h
  launcher/CMakeLists.txt
  launcher/InstanceCopyTask.cpp
  launcher/InstanceCreationTask.cpp
  launcher/InstanceCreationTask.h
  launcher/InstanceImportTask.cpp
  launcher/InstanceImportTask.h
  launcher/InstanceList.cpp
  launcher/InstanceList.h
  launcher/InstanceTask.cpp
  launcher/InstanceTask.h
  launcher/minecraft/VanillaInstanceCreationTask.cpp
  launcher/minecraft/VanillaInstanceCreationTask.h
  launcher/modplatform/atlauncher/ATLPackInstallTask.cpp
  launcher/modplatform/atlauncher/ATLPackInstallTask.h
  launcher/modplatform/flame/FlameAPI.cpp
  launcher/modplatform/flame/FlameAPI.h
  launcher/modplatform/flame/FlameInstanceCreationTask.cpp
  launcher/modplatform/flame/FlameInstanceCreationTask.h
  launcher/modplatform/flame/PackManifest.cpp
  launcher/modplatform/flame/PackManifest.h
  launcher/modplatform/helpers/OverrideUtils.cpp
  launcher/modplatform/helpers/OverrideUtils.h
  launcher/modplatform/legacy_ftb/PackFetchTask.cpp
  launcher/modplatform/legacy_ftb/PackFetchTask.h
  launcher/modplatform/legacy_ftb/PackInstallTask.cpp
  launcher/modplatform/legacy_ftb/PackInstallTask.h
  launcher/modplatform/modpacksch/FTBPackInstallTask.cpp
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.cpp
  launcher/modplatform/modrinth/ModrinthInstanceCreationTask.h
  launcher/modplatform/technic/SingleZipPackInstallTask.cpp
  launcher/modplatform/technic/SolderPackInstallTask.cpp
  launcher/modplatform/technic/SolderPackInstallTask.h
  launcher/tasks/Task.h
  launcher/ui/MainWindow.cpp
  launcher/ui/dialogs/NewInstanceDialog.cpp
  launcher/ui/dialogs/NewInstanceDialog.h
  launcher/ui/dialogs/ProgressDialog.cpp
  launcher/ui/pages/modplatform/VanillaPage.cpp
  launcher/ui/pages/modplatform/atlauncher/AtlPage.cpp
  launcher/ui/pages/modplatform/ftb/FtbPage.cpp
  launcher/ui/pages/modplatform/legacy_ftb/Page.cpp
  launcher/ui/pages/modplatform/legacy_ftb/Page.h
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
  launcher/ui/pages/modplatform/technic/TechnicPage.cpp
Labels: enhancement

#1172 Add missing includes to fix Qt 6.4 build
  launcher/ui/themes/BrightTheme.cpp
  launcher/ui/themes/DarkTheme.cpp
Labels: bug, simple change
