Repository PolyMC/PolyMC, pull requests merged in 2022-06, with the labels that each got.

#286 Prepare for Nix 2.7
  flake.nix
Labels: packaging

#718 Unset Qt High-DPI scaling policy
  launcher/main.cpp
Labels: bug

#708 Add support for custom User Agent
  launcher/Application.cpp
  launcher/Application.h
  launcher/net/Download.cpp
  launcher/net/PasteUpload.cpp
  launcher/net/Upload.cpp
  launcher/screenshots/ImgurAlbumCreation.cpp
  launcher/screenshots/ImgurUpload.cpp
  launcher/ui/pages/global/APIPage.cpp
  launcher/ui/pages/global/APIPage.ui
Labels: enhancement

#732 Add initial sorting function
  launcher/icons/IconList.cpp
  launcher/icons/IconList.h
Labels: enhancement

#709 Always store InstanceType
  launcher/BaseInstance.cpp
  launcher/InstanceList.cpp
  launcher/minecraft/MinecraftInstance.cpp
Labels: bug

#720 Fix legacy Forge issues
  libraries/launcher/net/minecraft/Launcher.java
Labels: bug

#770 Fix homepage URL in Technic's page
  launcher/ui/pages/modplatform/technic/TechnicPage.ui
Labels: bug

#773 Update toolbar when instance state changes
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
Labels: bug

#780 Fix mrpack manual import in languages that don't use dots
  launcher/ui/pages/modplatform/ImportPage.cpp
Labels: bug

#632 Fix lingering PolyMC icon in Dock on macOS
  launcher/Application.cpp
  launcher/Application.h
Labels: bug, macOS

#771 Fix some Modrinth `mrpack` import issues
  launcher/FileSystem.cpp
  launcher/FileSystem.h
  launcher/InstanceImportTask.cpp
  launcher/modplatform/modrinth/ModrinthPackManifest.cpp
  launcher/modplatform/modrinth/ModrinthPackManifest.h
Labels: bug

#679 Use CMake for Windows installer branding and version number
  .github/workflows/build.yml
  program_info/CMakeLists.txt
  program_info/win_install.nsi.in
Labels: bug, Windows

#759 Correctly handle disabled mods with metadata
  launcher/minecraft/mod/Mod.cpp
  launcher/minecraft/mod/Mod.h
  launcher/minecraft/mod/tasks/ModFolderLoadTask.cpp
Labels: bug

#714 Fix mod metadata tests
  launcher/Application.cpp
  launcher/Application.h
  launcher/CMakeLists.txt
  launcher/ModDownloadTask.cpp
  launcher/ModDownloadTask.h
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/launch/LauncherPartLaunch.cpp
  launcher/minecraft/mod/Mod.cpp
  launcher/minecraft/mod/ModFolderModel.cpp
  launcher/minecraft/mod/ModFolderModel.h
  launcher/minecraft/mod/ModFolderModel_test.cpp
  launcher/minecraft/mod/ResourcePackFolderModel.cpp
  launcher/minecraft/mod/TexturePackFolderModel.cpp
  launcher/minecraft/mod/tasks/LocalModUpdateTask.cpp
  launcher/minecraft/mod/tasks/ModFolderLoadTask.cpp
  launcher/minecraft/mod/tasks/ModFolderLoadTask.h
  launcher/modplatform/packwiz/Packwiz_test.cpp
  launcher/net/PasteUpload.cpp
  launcher/ui/GuiUtil.cpp
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
  launcher/ui/pages/global/LanguagePage.cpp
  launcher/ui/pages/global/LanguagePage.h
  launcher/ui/pages/global/LauncherPage.cpp
  launcher/ui/pages/global/LauncherPage.h
  launcher/ui/pages/global/LauncherPage.ui
  launcher/ui/pages/instance/LogPage.cpp
  launcher/ui/pages/instance/ModFolderPage.cpp
  launcher/ui/pages/instance/ModFolderPage.h
  launcher/ui/pages/instance/ScreenshotsPage.cpp
  launcher/ui/pages/instance/ScreenshotsPage.h
  launcher/ui/pages/instance/ServersPage.cpp
  launcher/ui/pages/instance/WorldListPage.cpp
  launcher/ui/pages/modplatform/ModPage.cpp
  launcher/ui/pages/modplatform/legacy_ftb/ListModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.h
Labels: bug

#634 More links for CF / Modrinth mods / modpacks
  launcher/modplatform/ModAPI.h
  launcher/modplatform/ModIndex.h
  launcher/modplatform/flame/FlameAPI.h
  launcher/modplatform/flame/FlameModIndex.cpp
  launcher/modplatform/flame/FlameModIndex.h
  launcher/modplatform/flame/FlamePackIndex.cpp
  launcher/modplatform/flame/FlamePackIndex.h
  launcher/modplatform/helpers/NetworkModAPI.cpp
  launcher/modplatform/helpers/NetworkModAPI.h
  launcher/modplatform/modrinth/ModrinthAPI.h
  launcher/modplatform/modrinth/ModrinthPackIndex.cpp
  launcher/modplatform/modrinth/ModrinthPackIndex.h
  launcher/modplatform/modrinth/ModrinthPackManifest.cpp
  launcher/modplatform/modrinth/ModrinthPackManifest.h
  launcher/ui/pages/modplatform/ModModel.cpp
  launcher/ui/pages/modplatform/ModModel.h
  launcher/ui/pages/modplatform/ModPage.cpp
  launcher/ui/pages/modplatform/ModPage.h
  launcher/ui/pages/modplatform/flame/FlamePage.cpp
  launcher/ui/pages/modplatform/flame/FlamePage.h
  launcher/ui/pages/modplatform/modrinth/ModrinthModModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthModModel.h
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
Labels: enhancement

#716 Hide index folder on Windows
  launcher/minecraft/mod/tasks/LocalModUpdateTask.cpp
Labels: bug, Windows

#633 Remove unused GH Workflows
  .github/workflows/backport.yml
  .github/workflows/pr-comment.yml
Labels: actions

#778 Track real CPU architecture for instances
  launcher/Application.cpp
  launcher/launch/steps/CheckJava.cpp
  launcher/launch/steps/CheckJava.h
Labels: simple change

#817 Don't create unnecessary folders when extracting ZIPs
  launcher/MMCZip.cpp
Labels: bug, simple change

#807 Add LGTM config
  lgtm.yml
Labels: simple change

#830 Replace old reference to launchermeta
  launcher/minecraft/MojangDownloadInfo.h
Labels: bug, simple change

#724 Resize PolyMC logo
  README.md
Labels: enhancement, simple change

#834 chore(flame): reword warning
  launcher/ui/pages/modplatform/flame/FlamePage.ui
Labels: simple change

#827 Workaround Qt bug to fix menu bar separators on macOS
  launcher/ui/MainWindow.cpp
Labels: bug, macOS, simple change

#837 fix(modrinth): fix sorting
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.cpp
Labels: bug

#826 Separate launch and kill instance actions
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
Labels: bug, enhancement
