Repository PolyMC/PolyMC, pull requests merged in 2022-07, with the labels that each got.

#785 Change formatting of JavaCheck
  libraries/javacheck/CMakeLists.txt
  libraries/javacheck/JavaCheck.java
Labels: enhancement

#652 Create a more clear hierarchy for the mods / resource packs / shaders pages
  launcher/CMakeLists.txt
  launcher/InstancePageProvider.h
  launcher/ui/pages/instance/ExternalResourcesPage.cpp
  launcher/ui/pages/instance/ExternalResourcesPage.h
  launcher/ui/pages/instance/ExternalResourcesPage.ui
  launcher/ui/pages/instance/ModFolderPage.cpp
  launcher/ui/pages/instance/ModFolderPage.h
  launcher/ui/pages/instance/ResourcePackPage.h
  launcher/ui/pages/instance/ShaderPackPage.h
  launcher/ui/pages/instance/TexturePackPage.h
Labels: enhancement

#863 update NewLaunch package name
  launcher/minecraft/launch/LauncherPartLaunch.cpp
Labels: priority, simple change

#845 Add news reader in the launcher
  launcher/CMakeLists.txt
  launcher/news/NewsEntry.cpp
  launcher/ui/MainWindow.cpp
  launcher/ui/dialogs/NewsDialog.cpp
  launcher/ui/dialogs/NewsDialog.h
  launcher/ui/dialogs/NewsDialog.ui
Labels: enhancement

#860 Show MC version of instance in status bar
  launcher/minecraft/MinecraftInstance.cpp
Labels: bug, simple change

#818 Always scale mod icons to the right size
  launcher/ui/pages/modplatform/ModModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.cpp
Labels: bug, simple change

#831 Add missing connections to the abort signal in some tasks
  launcher/minecraft/ComponentUpdateTask.cpp
  launcher/minecraft/MinecraftLoadAndCheck.cpp
  launcher/minecraft/MinecraftUpdate.cpp
  launcher/minecraft/MinecraftUpdate.h
  launcher/minecraft/PackProfile.cpp
  launcher/minecraft/auth/MinecraftAccount.cpp
  launcher/minecraft/auth/steps/YggdrasilStep.cpp
  launcher/minecraft/update/AssetUpdateTask.cpp
  launcher/minecraft/update/FMLLibrariesTask.cpp
  launcher/minecraft/update/LibrariesTask.cpp
Labels: bug, priority

#855 Improve the account selection window
  launcher/minecraft/auth/AccountData.cpp
  launcher/minecraft/auth/AccountList.cpp
  launcher/minecraft/auth/AccountList.h
  launcher/ui/pages/global/AccountListPage.cpp
Labels: enhancement

#869 fix: Add extra-cmake-modules to the nix build
  nix/default.nix
Labels: packaging

#870 Fix release builds
  launcher/ui/pages/global/AccountListPage.cpp
Labels: bug, simple change

#871 DCO: Allow remediation commits
  .github/dco.yml
Labels: simple change

#707 Add Performance related settings
  CMakeLists.txt
  launcher/Application.cpp
  launcher/BaseInstance.h
  launcher/CMakeLists.txt
  launcher/NullInstance.h
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/MinecraftInstance.h
  launcher/minecraft/launch/DirectJavaLaunch.cpp
  launcher/minecraft/launch/LauncherPartLaunch.cpp
  launcher/ui/pages/global/MinecraftPage.cpp
  launcher/ui/pages/global/MinecraftPage.ui
  launcher/ui/pages/instance/InstanceSettingsPage.cpp
  launcher/ui/pages/instance/InstanceSettingsPage.ui
  libraries/README.md
  libraries/gamemode/CMakeLists.txt
  libraries/gamemode/include/gamemode_client.h
Labels: enhancement

#794 Resolve JARs dynamically
  CMakeLists.txt
  launcher/Application.cpp
  launcher/Application.h
  launcher/JavaCommon.cpp
  launcher/JavaCommon.h
  launcher/java/JavaChecker.cpp
  launcher/java/JavaUtils.cpp
  launcher/java/JavaUtils.h
  launcher/launch/steps/CheckJava.cpp
  launcher/minecraft/launch/LauncherPartLaunch.cpp
  launcher/ui/pages/global/JavaPage.cpp
  launcher/ui/pages/instance/InstanceSettingsPage.cpp
  launcher/ui/widgets/JavaSettingsWidget.cpp
Labels: enhancement

#839 Some small fixes and improvements to modpacks
  launcher/InstanceImportTask.cpp
  launcher/minecraft/mod/ModFolderModel.cpp
  launcher/modplatform/flame/FileResolvingTask.cpp
  launcher/ui/pages/modplatform/ModModel.cpp
  launcher/ui/pages/modplatform/flame/FlameModel.cpp
  launcher/ui/pages/modplatform/flame/FlameModel.h
  launcher/ui/pages/modplatform/flame/FlamePage.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.h
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.ui
  launcher/ui/pages/modplatform/technic/TechnicModel.cpp
Labels: bug, enhancement

#890 Fix Technic instances using Forge
  launcher/modplatform/technic/TechnicPackProcessor.cpp
Labels: bug

#884 Updated FTB Classic layout
  launcher/ui/pages/modplatform/legacy_ftb/Page.ui
Labels: simple change

#851 Add WinGet Releaser
  .github/workflows/winget.yml
Labels: enhancement, packaging, Windows

#880 Make loader components not important
  launcher/InstanceImportTask.cpp
  launcher/modplatform/atlauncher/ATLPackInstallTask.cpp
  launcher/modplatform/modpacksch/FTBPackInstallTask.cpp
Labels: bug, simple change

#479 Implement updater on macOS
  .github/workflows/build.yml
  .github/workflows/trigger_builds.yml
  CMakeLists.txt
  buildconfig/BuildConfig.cpp.in
  buildconfig/BuildConfig.h
  cmake/MacOSXBundleInfo.plist.in
  launcher/Application.cpp
  launcher/CMakeLists.txt
  launcher/ui/MainWindow.cpp
  launcher/ui/pages/global/LauncherPage.cpp
  launcher/ui/pages/global/LauncherPage.ui
  launcher/updater/ExternalUpdater.h
  launcher/updater/MacSparkleUpdater.h
  launcher/updater/MacSparkleUpdater.mm
  launcher/updater/UpdateChecker.cpp
  launcher/updater/UpdateChecker.h
Labels: enhancement, macOS

#847 Rewrite polymc.6 in scdoc, build, and install it
  CMakeLists.txt
  program_info/CMakeLists.txt
  program_info/polymc.6.scd
  program_info/polymc.6.txt
Labels: enhancement

#678 Improvements around services with API keys
  CMakeLists.txt
  buildconfig/BuildConfig.cpp.in
  buildconfig/BuildConfig.h
  launcher/Application.cpp
  launcher/Application.h
  launcher/net/Download.cpp
  launcher/net/Download.h
  launcher/net/Upload.cpp
  launcher/net/Upload.h
  launcher/ui/dialogs/ModDownloadDialog.cpp
  launcher/ui/dialogs/ModDownloadDialog.h
  launcher/ui/dialogs/NewInstanceDialog.cpp
  launcher/ui/dialogs/NewInstanceDialog.h
  launcher/ui/pages/global/APIPage.cpp
  launcher/ui/pages/global/APIPage.ui
  launcher/ui/pages/global/AccountListPage.cpp
  launcher/ui/pages/modplatform/ImportPage.ui
Labels: enhancement

#810 Hide channel from version for tagged commits
  CMakeLists.txt
  buildconfig/BuildConfig.cpp.in
  buildconfig/BuildConfig.h
  cmake/GetGitRevisionDescription.cmake
  cmake/GetGitRevisionDescription.cmake.in
Labels: enhancement

#904 fix(nix): add stdenv.cc.cc.lib to GAME_LIBRARY_PATH
  nix/default.nix
Labels: simple change

#911 Fix release workflow
  .github/workflows/trigger_release.yml
Labels: simple change

#914 feat(actions): bring back qt caching
  .github/workflows/build.yml
Labels: enhancement, actions

#902 Fix JavaChecker on Windows
  launcher/java/JavaUtils.cpp
Labels: bug

#917 Fix translations stuff
  launcher/JavaCommon.cpp
Labels: bug, simple change

#913 Allow the cape to be changed without changing the skin
  launcher/ui/dialogs/SkinUploadDialog.cpp
  launcher/ui/dialogs/SkinUploadDialog.ui
Labels: enhancement, simple change

#929 Fix readability issue with placeholder text in the dark theme
  launcher/ui/themes/DarkTheme.cpp
Labels: bug, simple change

#934 fix(nix): only load stdenv.cc.cc.lib on NixOS
  nix/default.nix
Labels: bug, packaging, simple change

#936 fix: fix Java Checker on Windows, again
  launcher/java/JavaUtils.cpp
Labels: bug

#930 Add more Nix `meta` information
  nix/default.nix
Labels: enhancement, packaging, simple change

#932 Nix: switch to PolyMC libnbtplusplus
  flake.lock
  flake.nix
Labels: bug, packaging, simple change

#938 fix: fix translations for mod updater
  launcher/modplatform/flame/FlameCheckUpdate.cpp
  launcher/ui/dialogs/ModUpdateDialog.cpp
  launcher/ui/pages/instance/ExternalResourcesPage.ui
  launcher/ui/pages/instance/ModFolderPage.cpp
Labels: bug, simple change

#922 feat(actions): package and deliver qt6 tarballs
  .github/workflows/build.yml
  .github/workflows/trigger_release.yml
Labels: actions, packaging

#947 Use single-space unicode character for checkmark in mod list
  launcher/minecraft/MinecraftInstance.cpp
Labels: bug, simple change

#877 Fix "Play Offline" issues
  launcher/CMakeLists.txt
  launcher/minecraft/auth/steps/LauncherLoginStep.cpp
  launcher/minecraft/auth/steps/MinecraftProfileStep.cpp
  launcher/minecraft/auth/steps/MinecraftProfileStepMojang.cpp
  launcher/minecraft/auth/steps/XboxAuthorizationStep.cpp
  launcher/minecraft/auth/steps/XboxProfileStep.cpp
  launcher/minecraft/auth/steps/XboxUserStep.cpp
  launcher/net/NetUtils.h
Labels: bug

#893 Refactor filtering of environment variables
  launcher/Launcher.in
  launcher/java/JavaUtils.cpp
  launcher/java/JavaUtils.h
  nix/default.nix
Labels: enhancement

#952 Fix variable substitution in pre launch/post exit hooks
  launcher/launch/LaunchTask.cpp
  launcher/launch/LaunchTask.h
  launcher/launch/steps/PostLaunchCommand.cpp
  launcher/launch/steps/PreLaunchCommand.cpp
Labels: bug

#951 Hide the entire performance tab on the instance settings in non-Linux OSes
  launcher/ui/pages/instance/InstanceSettingsPage.cpp
Labels: bug

#956 Fix segmentation fault when using jar mods
  launcher/MMCZip.cpp
Labels: bug

#961 Fix filter in external resource pages not working
  launcher/ui/pages/instance/ExternalResourcesPage.cpp
Labels: bug

#958 Fix broken url in readme
  README.md
Labels: simple change

#974 Fix adding multiple accounts in Qt6
  launcher/QObjectPtr.h
  launcher/minecraft/auth/AccountList.cpp
Labels: bug

#699 Implement mod resolving for FTB
  launcher/modplatform/flame/FileResolvingTask.cpp
  launcher/modplatform/flame/FileResolvingTask.h
  launcher/modplatform/modpacksch/FTBPackInstallTask.cpp
  launcher/modplatform/modpacksch/FTBPackInstallTask.h
  launcher/modplatform/modpacksch/FTBPackManifest.cpp
  launcher/modplatform/modpacksch/FTBPackManifest.h
  launcher/ui/dialogs/ProgressDialog.cpp
  launcher/ui/pages/modplatform/ftb/FtbPage.cpp
Labels: bug, priority

#941 Bump to C++17
  CMakeLists.txt
  COPYING.md
  launcher/CMakeLists.txt
  launcher/InstanceImportTask.h
  launcher/MMCZip.cpp
  launcher/MMCZip.h
  launcher/minecraft/World.cpp
  launcher/minecraft/World.h
  launcher/modplatform/atlauncher/ATLPackInstallTask.h
  launcher/modplatform/legacy_ftb/PackInstallTask.h
  launcher/modplatform/technic/SingleZipPackInstallTask.h
  libraries/README.md
  libraries/optional-bare/CMakeLists.txt
  libraries/optional-bare/LICENSE.txt
  libraries/optional-bare/README.md
  libraries/optional-bare/include/nonstd/optional
Labels: enhancement

#549 Trash instances instead of deleting
  launcher/FileSystem.cpp
  launcher/FileSystem.h
  launcher/InstanceList.cpp
  launcher/InstanceList.h
  launcher/ui/MainWindow.cpp
  launcher/ui/MainWindow.h
Labels: enhancement
