Repository PolyMC/PolyMC, pull requests merged in 2022-02, with the labels that each got.

#129 Fixed the download menu putting the wrong name
  launcher/ui/pages/modplatform/flame/FlameModPage.cpp
  launcher/ui/pages/modplatform/flame/FlameModPage.h
  launcher/ui/pages/modplatform/modrinth/ModrinthModel.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.h
Labels: bug

#140 CI: Build AppImages
  .github/scripts/prepare_JREs.sh
  .github/workflows/build.yml
  README.md
  program_info/org.polymc.PolyMC.desktop.in
Labels: enhancement

#145 Update metadata
  CMakeLists.txt
  program_info/org.polymc.PolyMC.metainfo.xml.in
Labels: enhancement

#146 [MACOS] Move app data to Application Support
  launcher/Application.cpp
Labels: enhancement

#134 OpenBSD support and slackware build instructions
  BUILD.md
  launcher/UpdateController.cpp
  launcher/tools/MCEditTool.cpp
Labels: enhancement

#143 Link internal libraries statically
  CMakeLists.txt
  launcher/CMakeLists.txt
  libraries/iconfix/CMakeLists.txt
  libraries/rainbow/CMakeLists.txt
Labels: enhancement

#161 Add MSA-Client-ID override in UI
  launcher/Application.cpp
  launcher/Application.h
  launcher/CMakeLists.txt
  launcher/minecraft/auth/steps/MSAStep.cpp
  launcher/ui/pages/global/APIPage.cpp
  launcher/ui/pages/global/APIPage.h
  launcher/ui/pages/global/APIPage.ui
  launcher/ui/pages/global/AccountListPage.cpp
Labels: enhancement

#160 Show the current branch rather than "custom" in version string
  buildconfig/BuildConfig.cpp.in
Labels: enhancement, needs-review

#171 Change: set MACOSX_BUNDLE_GUI_IDENTIFIER to org.polymc (fixes org.multimc.PolyMC)
  CMakeLists.txt
Labels: enhancement

#131 Add Slackware package
  README.md
Labels: enhancement

#173 fix: improve code readability in Application.cpp
  launcher/Application.cpp
Labels: enhancement

#180 Detect MSA Client ID change
  launcher/LaunchController.cpp
  launcher/minecraft/auth/AccountData.cpp
  launcher/minecraft/auth/AccountData.h
  launcher/minecraft/auth/AccountList.cpp
  launcher/minecraft/auth/AccountTask.cpp
  launcher/minecraft/auth/AccountTask.h
  launcher/minecraft/auth/MinecraftAccount.cpp
  launcher/minecraft/auth/steps/MSAStep.cpp
  launcher/minecraft/auth/steps/MSAStep.h
Labels: enhancement

#174 Prepare readme for 1.1.0, mark unofficial packages as unofficial
  README.md
Labels: documentation

#169 Add issue template for RFCs
  .github/ISSUE_TEMPLATE/rfc.yml
Labels: documentation, enhancement, low

#158 CI: Release builds and workflow
  .github/workflows/build.yml
  .github/workflows/trigger_builds.yml
  .github/workflows/trigger_release.yml
Labels: enhancement, high, needs-review

#192 Drop legacy instances
  launcher/BaseInstance.cpp
  launcher/CMakeLists.txt
  launcher/InstanceCopyTask.cpp
  launcher/InstanceCreationTask.cpp
  launcher/InstanceImportTask.cpp
  launcher/InstanceList.cpp
  launcher/InstancePageProvider.h
  launcher/minecraft/MinecraftInstance.cpp
  launcher/minecraft/PackProfile.cpp
  launcher/minecraft/PackProfile.h
  launcher/minecraft/PackProfile_p.h
  launcher/minecraft/legacy/LegacyInstance.cpp
  launcher/minecraft/legacy/LegacyInstance.h
  launcher/minecraft/legacy/LegacyModList.cpp
  launcher/minecraft/legacy/LegacyModList.h
  launcher/minecraft/legacy/LegacyUpgradeTask.cpp
  launcher/minecraft/legacy/LegacyUpgradeTask.h
  launcher/modplatform/atlauncher/ATLPackInstallTask.cpp
  launcher/modplatform/legacy_ftb/PackInstallTask.cpp
  launcher/modplatform/modpacksch/FTBPackInstallTask.cpp
  launcher/modplatform/technic/TechnicPackProcessor.cpp
  launcher/ui/pages/instance/LegacyUpgradePage.cpp
  launcher/ui/pages/instance/LegacyUpgradePage.h
  launcher/ui/pages/instance/LegacyUpgradePage.ui
Labels: enhancement, low

#183 Fixed segfault in mod download
  launcher/ui/pages/modplatform/flame/FlameModPage.cpp
  launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp
Labels: needs-review

#199 Update translations URL
  buildconfig/BuildConfig.h
Labels: external

#203 Notify about needed AppBSD version
  README.md
Labels: needs-review

#207 Always tell Flame API which ModLoader we are using
  launcher/modplatform/flame/FlameModIndex.cpp
  launcher/ui/pages/modplatform/flame/FlameModModel.cpp
Labels: enhancement
